### ISSUE TITLE
Refactor user redirect when not logged in

### ISSUE THREAD

**Issue by Sensanaty** [Sensanaty/Spotlight#7]
Referencing #3 

I think we might be better off enveloping our `application.html.erb` in an if statement after all.

Right now, we have 2 `head` tags that don't always match up simply for a different body. This is problematic because we're going to run into caching/cookie problems from the presence of distinct heads, as well as some errors (that have already occured in attempted deployments).

A better solution is to write a simple `if` logic check to see whether a user is logged in or not, and to show them the relevant information based on that. The current way we're doing it is pretty messy in terms of maintainability.

@josh-unwin

**Comment by josh-unwin** [comment]
Yeah sure, I agree. Last night I ended up doing it that way for devise anyway (as shown), I can just modify that.
<img width="595" alt="Screenshot 2019-11-05 at 10 03 32" src="https://user-images.githubusercontent.com/49525488/68172750-b1e03300-ffb3-11e9-86e9-f367562ec23d.png">

**Comment by josh-unwin** [comment]
Leave it with me :)

**Comment by Sensanaty** [comment]
Cool, we can also throw in a nice little changing `title` tag in our `head` that'll display something like this using a simple ternary

![Screenshot from 2019-11-05 10-09-27](https://user-images.githubusercontent.com/24919018/68173087-c113b080-ffb4-11e9-8795-c3d08f39cd48.png)

![Screenshot from 2019-11-05 10-11-50](https://user-images.githubusercontent.com/24919018/68173090-c3760a80-ffb4-11e9-81b0-03285c66216d.png)
