### ISSUE TITLE
Smoother homepage experience

### ISSUE THREAD

**Issue by Sensanaty** [Sensanaty/Spotlight#71]
@josh-unwin 

The homepage looks amazing, but browsing through it is a bit janky.

I think a good implementation would be to have smooth scrolling to the anchor tags as well as a persistent(sticky) header, or at least a way to go back to the top of the page.

@loftlights @andreapmd  What's your opinions?

**Comment by josh-unwin** [comment]
The current landing page is more or less just filler at the moment, I'm not emotionally attached to any of it. 🙃

**Comment by Sensanaty** [comment]
Yeah I thought as much, just a thought i had using the current v
